export const CONFIG = {
  INITIAL_STABILITY: 100,

  PHASES: {
    STABLE: 0,
    WATCHING: 50,
    CONCERNED: 200,
    HOSTILE: 400,
  },

  EFFECTS: {
    TITLE_GLITCH_AT: 30,
    BUTTON_SHAKE_AT: 80,
    BUTTON_ESCAPE_AT: 180,
    BUTTON_AI_AT: 250,
  },
} as const;