export const CONFIG = {
  INITIAL_STABILITY: 100,

  PHASES: {
    STABLE: 0,
    WATCHING: 10,
    CONCERNED: 50,
    HOSTILE: 150,
  },

  EFFECTS: {
    TITLE_GLITCH_AT: 15,
    BUTTON_SHAKE_AT: 25,
    BUTTON_ESCAPE_AT: 50,
    BUTTON_AI_AT: 50,
  },
} as const;