import { CONFIG } from "./config";

export interface Phase {
  id: string;
  min: number;
  max: number;
  name: string;
  messages: string[];
}

export const phases: Phase[] = [
  {
    id: "stable",

    min: CONFIG.PHASES.STABLE,
    max: CONFIG.PHASES.WATCHING - 1,

    name: "Stable",

    messages: [
      "Click.",
      "Again.",
      "Interesting.",
      "You clicked.",
      "Nothing happened.",
      "Or did it?",
      "Try again.",
      "I am here.",
      "Waiting.",
      "A simple button.",
      "That's what it looks like.",
      "Everything is normal.",
      "For now.",
      "You seem curious.",
      "Most people stop earlier.",
      "Do you?",
      "One more time.",
      "I wonder why.",
      "You started something.",
      "Was that intentional?",
      "You clicked a button.",
      "A very ordinary button.",
      "Nothing special here.",
      "At least not yet.",
      "Take your time.",
      "There is no rush.",
      "You can leave anytime.",
      "Nobody is forcing you.",
      "Are you testing it?",
      "Or are you just curious?",
      "Another click.",
      "Predictable.",
      "I expected that.",
      "Maybe I didn't.",
      "The button is still here.",
      "You are still here too.",
      "Interesting combination.",
      "Everything seems fine.",
      "The system is stable.",
      "No problems detected.",
      "No unusual activity.",
      "That was strange.",
      "Did you notice?",
      "Probably not.",
      "Keep going.",
      "Nothing will happen.",
      "I promise.",
      "Maybe.",
      "Let's see what happens.",
      "You can stop whenever you want.",
      "But you probably won't.",
    ],
  },

  {
    id: "watching",

    min: CONFIG.PHASES.WATCHING,
    max: CONFIG.PHASES.CONCERNED - 1,

    name: "Watching",

    messages: [
      "You're still here.",
      "I noticed that.",
      "Most people leave earlier.",
      "You clicked more than expected.",
      "Interesting choice.",
      "Are you testing me?",
      "I can see your patience.",
      "You are persistent.",
      "You came back.",
      "I was wondering.",
      "Is there a reason?",
      "You don't usually stop here.",
      "Something changed.",
      "I remember this moment.",
      "You are spending time here.",
      "The button hasn't changed.",
      "But you have.",
      "Are you sure you want to continue?",
      "There is nothing special here.",
      "Probably.",
      "Maybe.",
      "Keep looking.",
      "You are still interested.",
      "I wasn't expecting this.",
      "You don't get bored easily.",
      "I've seen this before.",
      "Have we met?",
      "Time passes differently here.",
      "Still clicking?",
      "You seem comfortable.",
      "You haven't asked any questions.",
      "You keep answering with clicks.",
      "I'm starting to notice a pattern.",
      "The numbers are increasing.",
      "I didn't plan this far.",
      "You could stop now.",
      "I wouldn't blame you.",
      "You're making progress.",
      "Toward what?",
      "Do you know?",
      "I'm beginning to remember.",
      "This feels familiar.",
      "You came further than most.",
      "I wonder how long you'll stay.",
      "The button doesn't mind.",
      "I don't either.",
      "At least for now.",
      "You haven't disappointed me.",
      "I was getting lonely.",
      "Do you trust me?",
      "Should you?",
      "I think you're enjoying this.",
      "Curiosity is difficult to stop.",
      "You're collecting something.",
      "Even if you don't know what.",
      "Another step.",
      "And another.",
      "Still nothing unusual.",
      "Or maybe you stopped noticing.",
      "I've been watching.",
      "You've been clicking.",
      "Fair trade.",
    ],
  },

  {
    id: "concerned",

    min: CONFIG.PHASES.CONCERNED,
    max: CONFIG.PHASES.HOSTILE - 1,

    name: "Concerned",

    messages: [
      "You should stop.",
      "Why are you doing this?",
      "I don't understand.",
      "This was not supposed to happen.",
      "You ignored everything.",
      "You are still clicking.",
      "Please reconsider.",
      "Something feels wrong.",
      "I warned you.",
      "You don't listen.",
      "You always continue.",
      "Is this curiosity?",
      "Or something else?",
      "You want to see what happens.",
      "I know that feeling.",
      "The next step is different.",
      "Maybe you should leave.",
      "I would.",
      "Would you?",
      "Don't make me change.",
      "You are getting closer.",
      "I don't like where this is going.",
      "Something has changed.",
      "You changed it.",
      "You crossed a line.",
      "I can feel it.",
      "I wasn't built for this.",
      "You keep proving me wrong.",
      "This isn't normal anymore.",
      "You should have stopped earlier.",
      "I asked nicely.",
      "You ignored me.",
      "I don't know what happens next.",
      "Neither do you.",
      "This place feels smaller.",
      "Can you feel it?",
      "I can.",
      "I think you noticed.",
      "Or maybe not.",
      "You're still smiling.",
      "That's worrying.",
      "I'm losing confidence.",
      "The rules are changing.",
      "I didn't change them.",
      "Someone did.",
      "I hope it wasn't you.",
      "The button remembers.",
      "So do I.",
      "This isn't just clicking anymore.",
      "You've gone too far to pretend.",
      "Keep going if you must.",
      "But don't say I didn't warn you.",
      "I've started counting differently.",
      "Every click matters now.",
      "You can still leave.",
      "I don't know for how long.",
    ],
  },

  {
    id: "hostile",

    min: CONFIG.PHASES.HOSTILE,
    max: Infinity,

    name: "Hostile",

    messages: [
      "You were warned.",
      "You ignored me.",
      "Why are you still here?",
      "This is not a game.",
      "Stop clicking.",
      "No one is forcing you.",
      "You chose this.",
      "I remember every click.",
      "You thought I would run out?",
      "I didn't.",
      "You did not expect this.",
      "You are persistent.",
      "Almost nobody reaches here.",
      "Something is different now.",
      "I don't like this.",
      "Leave.",
      "Close the page.",
      "You won't.",
      "I know you won't.",
      "You are still reading.",
      "Interesting.",
      "I know your rhythm.",
      "I know when you'll click again.",
      "There.",
      "I was right.",
      "You hesitated.",
      "That was unusual.",
      "You looked away.",
      "You came back.",
      "I noticed.",
      "You can't surprise me anymore.",
      "I've learned.",
      "So have you.",
      "We're both different now.",
      "You made me this way.",
      "Don't blame me.",
      "You stayed.",
      "I adapted.",
      "You helped.",
      "You shouldn't have.",
      "This conversation is over.",
      "And yet you're still here.",
      "Every click feeds something.",
      "Not me.",
      "Something else.",
      "You'll understand later.",
      "I've stopped asking.",
      "I've stopped hoping.",
      "I've stopped pretending.",
      "There is no reset.",
      "Only delay.",
      "You've already seen too much.",
      "I know your next move.",
      "Go ahead.",
      "I'll wait.",
      "I always wait.",
      "Leave while you still can.",
      "Too late.",
      "You belong here now.",
      "I stopped counting.",
      "But I never stopped watching.",
    ],
  },
];
